<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <LangVersion>latest</LangVersion>
    <Version>1.0.1</Version>
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Irihi.Ursa" Version="2.2.0" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="2.2.0" />
    <PackageReference Include="ReactiveUI.Avalonia" Version="12.1.1" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
    <PackageReference Include="Semi.Avalonia" Version="12.0.1" />
    <ProjectReference Include="..\TangdouDownloader.Core\TangdouDownloader.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
</Project>
